### PR TITLE
Added pycache in .gitignore

### PR DESCRIPTION
**Pull request by SubhradeepSS**
Issue #8 : Added pycache in .gitignore

### CODE REVIEW

**Comment by SubhradeepSS** [comment]
Issue #9

**Comment by nahimilega** [comment]
Can you please squash both the git commits to one. :)
And maybe have a more descriptive commit message.
Maybe something like ```Add pycache in .gitignore```

**Comment by SubhradeepSS** [comment]
@nahimilega can u please help me how to squash my commits into one?

**Comment by SubhradeepSS** [comment]
@nahimilega should I close this PR and create a new PR?

**Comment by nahimilega** [comment]
@SubhradeepSS You may refer to this https://github.com/wprig/wprig/wiki/How-to-squash-commits.
Basically, execute ```git rebase -i master``` command and squash the commits.
Then force push it. You don't need to make a separate PR ;)

**Comment by SubhradeepSS** [comment]
@nahimilega  I am having problem in squashing commits.Is squashing the commits a must for approval?

**Comment by nahimilega** [comment]
> @nahimilega I am having problem in squashing commits

It might seep difficult at first, but once you get to know how it is done, it's pretty easy.
You may refer to this tutorial https://www.youtube.com/watch?v=viY1BbKZhSI

If you still face issue, we will be happy to help you :)


> Is squashing the commits a must for approval?

Keeping the git history clean and readable is an important part of any project, and especially open source projects(like this).
https://dzone.com/articles/how-and-why-to-keep-your-git-commit-history-clean
https://about.gitlab.com/blog/2018/06/07/keeping-git-commit-history-clean/

Hence i believe squashing is important ;)

**Comment by SubhradeepSS** [comment]
@nahimilega Thanks for helping me out.
I have successfully squashed the commits.
Please review now.

**Comment by nahimilega** [comment]
Maybe you can make your commit message more descriptive 
Maybe something like ```Add pycache in .gitignore```

PS: I know you are thinking "what the hell", what is the problem with the current iterating of PR I am being too bossy and stuff like that(I used to think the same xD). But few years down the line, when you are working on a big project with maybe 100s of other engineers, then you will understand the importance of such small stuff ;)
@LakshyAAAgrawal @BhavyaC16 Thoughts?

**Comment by SubhradeepSS** [comment]
> Maybe you can make your commit message more descriptive
> Maybe something like `Add pycache in .gitignore`
> 
> PS: I know you are thinking "what the hell", what is the problem with the current iterating of PR I am being too bossy and stuff like that(I used to think the same xD). But few years down the line, when you are working on a big project with maybe 100s of other engineers, then you will understand the importance of such small stuff ;)

@nahimilega Not at all!
I like things to be done in the most perfect way.

**Comment by SubhradeepSS** [comment]
> > Maybe you can make your commit message more descriptive
> > Maybe something like `Add pycache in .gitignore`
> > PS: I know you are thinking "what the hell", what is the problem with the current iterating of PR I am being too bossy and stuff like that(I used to think the same xD). But few years down the line, when you are working on a big project with maybe 100s of other engineers, then you will understand the importance of such small stuff ;)
> 
> @nahimilega Not at all!
> I like things to be done in the most perfect way.

Updated the changes.Please review @nahimilega
Any further changes required?

**Comment by nahimilega** [comment]
> Any further changes required?

Looks fine to me, @LakshyAAAgrawal could you please take a final look and merge this PR ;)

**Comment by SubhradeepSS** [comment]
@BhavyaC16 @nahimilega  please review this PR

**Comment by SubhradeepSS** [comment]
@atm1504 @chanmol1999 This is the unmerged PR.Please tell the respective mentors to approve this PR and update my score in the leaderboard.

**Pull request closed without merging**
